# Generated by Django 4.2.3 on 2023-08-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('mistry', 'mistry'), ('Thirled', 'Thriled'), ('Horror', 'Horror'), ('poem', 'poem')], max_length=30)),
                ('first_pub', models.DateField(auto_now_add=True)),
                ('last_pub', models.DateField()),
            ],
        ),
    ]
